---

###
### Enable sudo (required for docker service)
###
sudo: required


###
### Language
###
language: minimal


###
### Add services
###
services:
  - docker


###
### Build Matrix
###
env:
  matrix:
    - VERSION=2.3-awshelm HELM=2.11
    - VERSION=2.4-awshelm HELM=2.11
    - VERSION=2.5-awshelm HELM=2.11
    - VERSION=2.6-awshelm HELM=2.11
    - VERSION=2.7-awshelm HELM=2.11
    - VERSION=2.8-awshelm HELM=2.11
    - VERSION=latest-awshelm HELM=2.11
    - VERSION=2.3-awshelm HELM=2.12
    - VERSION=2.4-awshelm HELM=2.12
    - VERSION=2.5-awshelm HELM=2.12
    - VERSION=2.6-awshelm HELM=2.12
    - VERSION=2.7-awshelm HELM=2.12
    - VERSION=2.8-awshelm HELM=2.12
    - VERSION=latest-awshelm HELM=2.12
    - VERSION=2.3-awshelm HELM=2.13
    - VERSION=2.4-awshelm HELM=2.13
    - VERSION=2.5-awshelm HELM=2.13
    - VERSION=2.6-awshelm HELM=2.13
    - VERSION=2.7-awshelm HELM=2.13
    - VERSION=2.8-awshelm HELM=2.13
    - VERSION=latest-awshelm HELM=2.13
    - VERSION=2.3-awshelm HELM=2.14
    - VERSION=2.4-awshelm HELM=2.14
    - VERSION=2.5-awshelm HELM=2.14
    - VERSION=2.6-awshelm HELM=2.14
    - VERSION=2.7-awshelm HELM=2.14
    - VERSION=2.8-awshelm HELM=2.14
    - VERSION=latest-awshelm HELM=2.14
    - VERSION=2.3-awshelm HELM=2.15
    - VERSION=2.4-awshelm HELM=2.15
    - VERSION=2.5-awshelm HELM=2.15
    - VERSION=2.6-awshelm HELM=2.15
    - VERSION=2.7-awshelm HELM=2.15
    - VERSION=2.8-awshelm HELM=2.15
    - VERSION=latest-awshelm HELM=2.15
    - VERSION=2.3-awskops KOPS=1.8
    - VERSION=2.4-awskops KOPS=1.8
    - VERSION=2.5-awskops KOPS=1.8
    - VERSION=2.6-awskops KOPS=1.8
    - VERSION=2.7-awskops KOPS=1.8
    - VERSION=2.8-awskops KOPS=1.8
    - VERSION=latest-awskops KOPS=1.8
    - VERSION=2.3-awskops KOPS=1.9
    - VERSION=2.4-awskops KOPS=1.9
    - VERSION=2.5-awskops KOPS=1.9
    - VERSION=2.6-awskops KOPS=1.9
    - VERSION=2.7-awskops KOPS=1.9
    - VERSION=2.8-awskops KOPS=1.9
    - VERSION=latest-awskops KOPS=1.9
    - VERSION=2.3-awskops KOPS=1.10
    - VERSION=2.4-awskops KOPS=1.10
    - VERSION=2.5-awskops KOPS=1.10
    - VERSION=2.6-awskops KOPS=1.10
    - VERSION=2.7-awskops KOPS=1.10
    - VERSION=2.8-awskops KOPS=1.10
    - VERSION=latest-awskops KOPS=1.10
    - VERSION=2.3-awskops KOPS=1.11
    - VERSION=2.4-awskops KOPS=1.11
    - VERSION=2.5-awskops KOPS=1.11
    - VERSION=2.6-awskops KOPS=1.11
    - VERSION=2.7-awskops KOPS=1.11
    - VERSION=2.8-awskops KOPS=1.11
    - VERSION=latest-awskops KOPS=1.11
    - VERSION=2.3-awskops KOPS=1.12
    - VERSION=2.4-awskops KOPS=1.12
    - VERSION=2.5-awskops KOPS=1.12
    - VERSION=2.6-awskops KOPS=1.12
    - VERSION=2.7-awskops KOPS=1.12
    - VERSION=2.8-awskops KOPS=1.12
    - VERSION=latest-awskops KOPS=1.12
    - VERSION=2.3-awskops KOPS=1.13
    - VERSION=2.4-awskops KOPS=1.13
    - VERSION=2.5-awskops KOPS=1.13
    - VERSION=2.6-awskops KOPS=1.13
    - VERSION=2.7-awskops KOPS=1.13
    - VERSION=2.8-awskops KOPS=1.13
    - VERSION=latest-awskops KOPS=1.13
    - VERSION=2.3-awskops KOPS=1.14
    - VERSION=2.4-awskops KOPS=1.14
    - VERSION=2.5-awskops KOPS=1.14
    - VERSION=2.6-awskops KOPS=1.14
    - VERSION=2.7-awskops KOPS=1.14
    - VERSION=2.8-awskops KOPS=1.14
    - VERSION=latest-awskops KOPS=1.14
    - VERSION=2.3-awsk8s
    - VERSION=2.4-awsk8s
    - VERSION=2.5-awsk8s
    - VERSION=2.6-awsk8s
    - VERSION=2.7-awsk8s
    - VERSION=2.8-awsk8s
    - VERSION=latest-awsk8s
    - VERSION=2.3-aws
    - VERSION=2.4-aws
    - VERSION=2.5-aws
    - VERSION=2.6-aws
    - VERSION=2.7-aws
    - VERSION=2.8-aws
    - VERSION=latest-aws
    - VERSION=2.3-azure
    - VERSION=2.4-azure
    - VERSION=2.5-azure
    - VERSION=2.6-azure
    - VERSION=2.7-azure
    - VERSION=2.8-azure
    - VERSION=latest-azure
    - VERSION=2.3-infra
    - VERSION=2.4-infra
    - VERSION=2.5-infra
    - VERSION=2.6-infra
    - VERSION=2.7-infra
    - VERSION=2.8-infra
    - VERSION=latest-infra
    - VERSION=2.3-tools
    - VERSION=2.4-tools
    - VERSION=2.5-tools
    - VERSION=2.6-tools
    - VERSION=2.7-tools
    - VERSION=2.8-tools
    - VERSION=latest-tools
    - VERSION=2.3
    - VERSION=2.4
    - VERSION=2.5
    - VERSION=2.6
    - VERSION=2.7
    - VERSION=2.8
    - VERSION=latest


###
### Install requirements
###
install:
  - retry() {
      for ((n=0; n<10; n++)); do
        echo "[${n}] ${*}";
        if eval "${*}"; then
          return 0;
        fi;
      done;
      return 1;
    }


###
### Check generation changes, build and test
###
before_script:
  - retry make lint
  - retry make build TAG=${VERSION} KOPS=${KOPS=} HELM=${HELM=}
  - retry make test  TAG=${VERSION}


###
### Push to Dockerhub
###
script:
  # Push to docker hub on success
  - if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      while ! make login USER="${DOCKER_USERNAME}" PASS="${DOCKER_PASSWORD}"; do sleep 1; done;
      if [ -n "${TRAVIS_TAG}" ]; then
        while ! make push TAG="${VERSION}${KOPS=}${HELM=}-${TRAVIS_TAG}"; do sleep 1; done;
      elif [ "${TRAVIS_BRANCH}" == "master" ]; then
        while ! make push TAG=${VERSION}${KOPS=}${HELM=}; do sleep 1; done;
      elif [[ ${TRAVIS_BRANCH} =~ ^(release-[.0-9]+.*)$ ]]; then
        while ! make push TAG="${VERSION}${KOPS=}${HELM=}-${TRAVIS_BRANCH}"; do sleep 1; done;
      else
        echo "Skipping branch ${TRAVIS_BRANCH}";
      fi
    else
      echo "Skipping push on PR";
    fi
