---

name: Ansible Kops
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+*'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Adding all targets and only run them if they exist.
        # Prevents us from forgetting to update this in case
        # we add new envs in terragrunt.
        version:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "2.8"
          - "2.9"
          - latest
        kops:
          - "1.8"
          - "1.9"
          - "1.10"
          - "1.11"
          - "1.12"
          - "1.13"
          - "1.14"
          - "1.15"
          - "1.16"

    name: "[ Ansible ${{ matrix.version }} (Kops ${{ matrix.kops }}) ]"
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Show environment
        run: |
          env

      - name: Build
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make build ANSIBLE=${VERSION}-awskops KOPS=${KOPS}
        env:
          VERSION: ${{ matrix.version }}
          KOPS: ${{ matrix.kops }}

      - name: Test
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make test ANSIBLE=${VERSION}-awskops KOPS=${KOPS}
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
        env:
          VERSION: ${{ matrix.version }}
          KOPS: ${{ matrix.kops }}
