---

name: Ansible Helm
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+*'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Adding all targets and only run them if they exist.
        # Prevents us from forgetting to update this in case
        # we add new envs in terragrunt.
        version:
          - "2.3"
          - "2.4"
          - "2.5"
          - "2.6"
          - "2.7"
          - "2.8"
          - "2.9"
          - latest
        helm:
          - "2.11"
          - "2.12"
          - "2.13"
          - "2.14"
          - "2.15"
          - "3.0"
          - "3.1"

    name: "[ Ansible ${{ matrix.version }} (Helm ${{ matrix.helm }}) ]"
    steps:

      - name: Checkout repository
        uses: actions/checkout@master

      - name: Show environment
        run: |
          env

      - name: Build
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make build ANSIBLE=${VERSION}-awshelm HELM=${HELM}
        env:
          VERSION: ${{ matrix.version }}
          HELM: ${{ matrix.helm }}

      - name: Test
        run: |
          retry() {
            for ((n=0; n<10; n++)); do
              echo "[${n}] ${*}";
              if eval "${*}"; then
                return 0;
              fi;
            done;
            return 1;
          }
          retry make test ANSIBLE=${VERSION}-awshelm HELM=${HELM}
          git diff --quiet || { echo "Build Changes"; git diff; git status; false; }
        env:
          VERSION: ${{ matrix.version }}
          HELM: ${{ matrix.helm }}
